apiVersion: v1
kind: Service
metadata:
  name: webpage
  labels:
    app: webpage
spec:
  ports:
    - port: 80
      nodePort: 30003
  selector:
    app: webpage
    tier: frontend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  labels:
    app: webpage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: webpage
  labels:
    app: webpage
spec:
  selector:
    matchLabels:
      app:  webpage
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app:  webpage
        tier: frontend
    spec:
      containers:
      - image: httpd
        name:  webpage
        
        ports:
        - containerPort: 80
          name: webpage
        volumeMounts:
        - name: persistent-storage
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: pv-claim